[package]
name = "offchain"
version = "0.1.0"
authors = ["felipeargento <felipe@cartesi.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dispatcher = { path = "../dispatcher-v2/dispatcher"}

async-trait = "0.1"
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "28c5c4f" }
ethabi = { version = "14.0.0", default-features = false }
futures = "0.3"
im = "15.0.0"
serde_json = "1.0"
snafu = "0.6"
url = { version = "2.2.1", default-features = false }

[build-dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "28c5c4f" }
serde_json = "1.0"
